[package]
name = "confium-store-pkcs11"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "pkcs11", "hsm", "storage", "confium"]
description = "PKCS#11 v3.0 wrapping backend for Confium key storage"
documentation = "https://docs.rs/confium-store-pkcs11"

[lib]
name = "confium_store_pkcs11"
crate-type = ["cdylib", "rlib"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
confium-store = { workspace = true }
cryptoki = "0.12"
inventory = { workspace = true }

[dev-dependencies]
tempfile = "3"
