[package]
name = "confium-xmldsig"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "XMLDSig and Exclusive C14N for XML document signing"
keywords = ["crypto", "threshold", "confium"]

[dependencies]
serde = { workspace = true }
snafu = { workspace = true }

[lib]
crate-type = ["rlib"]
