[package]
name = "confium-openssl-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "OpenSSL 3.0 provider using Confium for signing"
keywords = ["crypto", "threshold", "confium"]

[dependencies]
serde = { workspace = true }
snafu = { workspace = true }

[lib]
crate-type = ["rlib"]
