[package]
name = "confium-openssl-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"
description = "OpenSSL 3.0 provider using Confium for threshold signing"
documentation = "https://docs.rs/confium-openssl-provider"
keywords = ["crypto", "openssl", "provider", "threshold", "confium"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["rlib"]
