[package]
name = "confium"
version = "0.1.2"
authors = ["Ribose Open <open.source@ribose.com>"]
edition = "2024"
rust-version = "1.85"
description = "Open-source distributed trust store framework"
homepage = "https://www.confium.org/"
repository = "https://github.com/confium/confium"
categories = ["authentication", "cryptography"]
license = "BSD-2-Clause"

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading = "0.8"
snafu = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[package.metadata.nix]
# Toggle app flake output
app = true
# Toggle flake outputs that build (checks, package and app)
build = true
