[package]
name = "confium"
version = "0.1.1"
authors = ["Ribose Open <open.source@ribose.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading = "0.7"
slog = "2.5"
slog-stdlog = "4.1"
slog-term = "2.6"
slog-async = "2.5"
snafu = "0.6"
