[package]
name = "confium-tc-elgamal-p256"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"
description = "Threshold ElGamal encryption over P-256 for Confium"
documentation = "https://docs.rs/confium-tc-elgamal-p256"
keywords = ["crypto", "elgamal", "threshold", "encryption", "p256"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
sha2 = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
p256 = { workspace = true, features = ["ecdsa", "arithmetic"] }
zeroize = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lib]
crate-type = ["rlib"]
