[package]
name = "confium-tc-ecies-p256"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "Threshold ECIES over P-256"
keywords = ["crypto", "threshold", "confium"]

[dependencies]
serde = { workspace = true }
snafu = { workspace = true }

[lib]
crate-type = ["rlib"]
