[package]
name = "confium-tc-ecies-p256"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"
description = "Threshold ECIES with ECDH and AES-256-GCM over P-256 for Confium"
documentation = "https://docs.rs/confium-tc-ecies-p256"
keywords = ["crypto", "ecies", "ecdh", "aes-gcm", "threshold"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
p256 = { workspace = true, features = ["ecdsa", "arithmetic"] }
sha2 = { workspace = true }
aes-gcm = { workspace = true }

[lib]
crate-type = ["rlib"]
