[package]
name = "confium-tc-ecies-p256"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "confium-tc-ecies-p256 — part of the Confium framework"
keywords = ["crypto", "threshold", "p256", "confium"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
p256 = { workspace = true }
sha2 = { workspace = true }

[lib]
crate-type = ["rlib"]
