[package]
name = "confium-publish"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "publish", "registry", "plugin", "confium"]
description = "Author tool for publishing Confium plugins to the registry"
documentation = "https://docs.rs/confium-publish"

[lib]
name = "confium_publish"
path = "src/lib.rs"

[[bin]]
name = "confium-publish"
path = "src/main.rs"


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
confium-api = { workspace = true }
confium-core = { workspace = true }
clap = { workspace = true }
libloading = { workspace = true }
snafu = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
