[package]
name = "confium-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "store", "key", "persistence", "confium"]
description = "Compartmentalized key and secret persistence for Confium"
documentation = "https://docs.rs/confium-store"

[lib]
name = "confium_store"
crate-type = ["cdylib", "rlib"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
inventory = { workspace = true }
snafu = { workspace = true }

[dev-dependencies]
tempfile = "3"
