[package]
name = "confium-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Confium Store: compartmentalized key/secret persistence"

[dependencies]
confium-api = { workspace = true }
