[package]
name = "confium-tc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "Threshold cryptography primitives: session, coordinator, reshare, KEM"
keywords = ["crypto", "threshold", "tc", "frost", "confium"]

[lib]
crate-type = ["rlib"]

[dependencies]
confium-api = { workspace = true }
confium-net = { workspace = true }
confium-store = { workspace = true }
hmac = { workspace = true }
inventory = { workspace = true }
sha2 = { workspace = true }
snafu = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
data-encoding = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }
