[package]
name = "confium-net-tcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "TCP transport for Confium (tcp://, tcp+tls://)"

[dependencies]
confium-net = { workspace = true }
inventory = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }

[dev-dependencies]
confium-net = { workspace = true }
