[package]
name = "confium-cert"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "X.509 certificate and CSR types with hierarchical path validation for Confium"
keywords = ["crypto", "x509", "cert", "pki", "confium"]

[dependencies]
serde = { workspace = true }
snafu = { workspace = true }
thiserror = { workspace = true }
x509-cert = { workspace = true }
der = { workspace = true }
spki = { workspace = true }
chrono = { workspace = true }
data-encoding = { workspace = true }
sha2 = { workspace = true }

[lib]
crate-type = ["rlib"]
