[package]
name = "confium-tc-frost-p256"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "FROST threshold signature over ECDSA P-256"
keywords = ["crypto", "frost", "threshold", "ecdsa", "p256"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
p256 = { workspace = true, features = ["ecdsa", "arithmetic"] }
sha2 = { workspace = true }
rand_core = { workspace = true }
elliptic-curve = { workspace = true, features = ["pkcs8", "sec1"] }
hex = { workspace = true }

[lib]
crate-type = ["rlib"]
