[package]
name = "confium-tc-gg18"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "ecdsa", "threshold", "gg18", "confium"]
description = "GG18 threshold ECDSA for Confium"
documentation = "https://docs.rs/confium-tc-gg18"

[lib]
crate-type = ["rlib"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
confium-tc = { workspace = true }
crypto-bigint = "0.5"
elliptic-curve = { version = "0.13", features = ["digest", "sec1"] }
hex = { version = "0.4" }
inventory = { workspace = true }
p256 = { version = "0.13", features = ["arithmetic", "ecdsa", "expose-field", "pkcs8", "serde"] }
sha2 = { workspace = true }
snafu = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
p256 = { version = "0.13", features = ["arithmetic", "ecdsa", "expose-field", "pem", "pkcs8"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
rand_core = { version = "0.6", default-features = false }
