[package]
name = "confium-store-openpgp-card"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"
description = "OpenPGP card backend (YubiKey, Nitrokey) for Confium store"
documentation = "https://docs.rs/confium-store-openpgp-card"
keywords = ["crypto", "openpgp", "yubikey", "smartcard", "confium"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["rlib"]
