[package]
name = "confium-net-quic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "quic", "transport", "threshold", "confium"]
description = "QUIC transport for Confium multi-party threshold protocols"
documentation = "https://docs.rs/confium-net-quic"


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
confium-net = { workspace = true }
inventory = { workspace = true }
url = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
confium-net = { workspace = true }
