[package]
name = "confium-attributes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
description = "Attribute-based threshold party selection"
keywords = ["crypto", "threshold", "attributes", "predicates", "confium"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["rlib"]
