[package]
name = "confium-sandbox-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "wasm", "sandbox", "browser", "confium"]
description = "WASM sandbox for browser-based Confium director signing"
documentation = "https://docs.rs/confium-sandbox-wasm"

[lib]
crate-type = ["rlib"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
snafu = { workspace = true }
wasmtime = { workspace = true }

[dev-dependencies]
wasmtime = { workspace = true, features = ["wat"] }
wat = "1"
