[package]
name = "confium-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Confium Network: transport abstraction for multi-party protocols"

[dependencies]
confium-api = { workspace = true }
inventory = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }
