[package]
name = "confium-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
categories = ["cryptography", "authentication"]
readme = "README.md"
repository.workspace = true
keywords = ["crypto", "network", "transport", "threshold", "confium"]
description = "Network transport abstraction for Confium multi-party protocols"
documentation = "https://docs.rs/confium-net"


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
inventory = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }
