name: tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test

      # install ruby
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      # install os-specific build deps and environment
      - name: install os-specific build deps and environment (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt -y install libbotan-2-dev cmake make g++
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$PWD/plugins/hash-botan/build/libcfm-hash-botan.so" >> $GITHUB_ENV

      - name: install os-specific build deps and environment (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install botan
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$PWD/plugins/hash-botan/build/libcfm-hash-botan.dylib" >> $GITHUB_ENV

      - name: install os-specific build deps and environment (Windows)
      # install deps with pacboy. It is slower for single lib but ubiquitous
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -eux
          pacman --noconfirm -S --needed pactoys
          pacboy sync --noconfirm libbotan:p
          echo "RUBY_DLL_PATH=$(cygpath -w $PWD/target/debug)" >> $GITHUB_ENV
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$(cygpath -w $PWD/plugins/hash-botan/build/libcfm-hash-botan.dll)" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=MSYS Makefiles" >> $GITHUB_ENV

      # prepare to build
      - name: install test dependencies
        working-directory: confium-ruby
        run: |
          bundle

      # build plugin
      - name: build plugin
        run: |
          mkdir plugins/hash-botan/build
          cd plugins/hash-botan/build
          cmake ..
          make

      # ruby tests
      - name: ruby tests
        shell: bash
        run: |
          export LD_LIBRARY_PATH=$PWD/target/debug
          export CONFIUM_LIBRARY_PATH=$PWD/target/debug
          cd confium-ruby
          bundle exec rspec
