name: tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
