name: tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test

      # install os-specific build deps and environment
      - name: install os-specific build deps and environment (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt -y install libbotan-2-dev cmake make g++

      - name: install os-specific build deps and environment (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install botan

      - name: install os-specific build deps and environment (Windows)
      # install deps with pacboy. It is slower for single lib but ubiquitous
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -eux
          pacman --noconfirm -S --needed pactoys
          pacboy sync --noconfirm libbotan:p

      # build plugin
      - name: build plugin
        run: |
          mkdir plugins/hash-botan/build
          cd plugins/hash-botan/build
          cmake ..
          make
