name: tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            env:
              CFM_HASH_BOTAN_PLUGIN_PATH: plugins/hash-botan/build/libcfm-hash-botan.so
          - os: macos-latest
            env:
              CFM_HASH_BOTAN_PLUGIN_PATH: plugins/hash-botan/build/libcfm-hash-botan.dylib
          - os: windows-latest
            cmake_opts: -G "MSYS Makefiles"
            env:
              CFM_HASH_BOTAN_PLUGIN_PATH:

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test

      # install ruby
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      # install os-specific build deps
      - name: install os-specific build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt -y install libbotan-2-dev cmake make g++
      - name: install os-specific build deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install botan
      - name: install os-specific build deps (Windows)
      # install deps with pacboy. It is slower for single lib but ubiquitous
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -eux
          pacman --noconfirm -S --needed pactoys
          pacboy sync --noconfirm libbotan:p

      # prepare to build
      - name: prepare to build
        run: |
          gem install ffi rspec
          mkdir plugins/hash-botan/build

      # build plugin
      - name: build plugin
        run: |
          cd plugins/hash-botan/build
          cmake ${{ matrix.cmake_opts }} ..
          make

      # ruby tests
      - name: ruby tests
        env: ${{ matrix.env }}
        shell: bash
        run: |
          export LD_LIBRARY_PATH=$PWD/target/debug
          if [[ "$OSTYPE" == *msys* ]]; then
            export RUBY_DLL_PATH="$(cygpath -w $PWD/target/debug)"
            export CFM_HASH_BOTAN_PLUGIN_PATH="$(cygpath -w $PWD/plugins/hash-botan/build/libcfm-hash-botan.dll)"
          fi
          rspec spec/
