name: test-and-publish

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/test-and-publish.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
  publish:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo publish
      - name: cargo publish
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
#          dry-run: true
