name: tests

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # install rust
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      # cargo build
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
      # cargo tests
      - name: cargo tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test

      # install os-specific build deps and environment
      - name: install os-specific build deps and environment (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt -y install libbotan-2-dev cmake make g++
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$PWD/plugins/hash-botan/build/libcfm-hash-botan.so" >> $GITHUB_ENV

      - name: install os-specific build deps and environment (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install botan
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$PWD/plugins/hash-botan/build/libcfm-hash-botan.dylib" >> $GITHUB_ENV


      - name: install MSys and Windows-specific dependencies
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          pacboy: >-
            toolchain:p
            cmake:p
            libbotan:p

      # build plugin
      - name: build plugin
        if: runner.os == 'Windows'
        shell:  msys2 {0}
        run: |
          set -eux
          echo "CFM_HASH_BOTAN_PLUGIN_PATH=$(cygpath -w $PWD/plugins/hash-botan/build/libcfm-hash-botan.dll)" >> $GITHUB_ENV
          mkdir plugins/hash-botan/build
          cd plugins/hash-botan/build
          cmake ..
          cmake --build .

      - name: build plugin
        if: runner.os != 'Windows'
        shell:  bash
        run: |
          mkdir plugins/hash-botan/build
          cd plugins/hash-botan/build
          cmake ..
          make
